@echo off
del /F %~dp0.mode-html5
del /F %~dp0.mode-mingw
del /F %~dp0Qt\'
del /F %~dp0Qt\CMakeCache.txt
rmdir /S/Q %~dp0Qt\CMakeFiles\
del /F %~dp0Qt\CTestTestfile.cmake
del /F %~dp0Qt\Makefile
del /F %~dp0Qt\cmake_install.cmake
del /F %~dp0Qt\config.opt
del /F %~dp0Qt\config.opt.in
del /F %~dp0Qt\config.redo.bat
del /F %~dp0Qt\config.summary
rmdir /S/Q %~dp0Qt\config.tests\
rmdir /S/Q %~dp0Qt\qtbase\CMakeFiles\
del /F %~dp0Qt\qtbase\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\Makefile
del /F %~dp0Qt\qtbase\bin\cmake_automoc_parser.exe
del /F %~dp0Qt\qtbase\bin\moc.exe
del /F %~dp0Qt\qtbase\bin\qt-cmake-create.bat
del /F %~dp0Qt\qtbase\bin\qt-cmake-private-install.cmake
del /F %~dp0Qt\qtbase\bin\qt-cmake-private.bat
del /F %~dp0Qt\qtbase\bin\qt-cmake-standalone-test.bat
del /F %~dp0Qt\qtbase\bin\qt-cmake.bat
del /F %~dp0Qt\qtbase\bin\qt-configure-module.bat
del /F %~dp0Qt\qtbase\bin\qt-internal-configure-examples.bat
del /F %~dp0Qt\qtbase\bin\qt-internal-configure-tests.bat
del /F %~dp0Qt\qtbase\bin\syncqt.exe
del /F %~dp0Qt\qtbase\bin\tracegen.exe
del /F %~dp0Qt\qtbase\bin\tracepointgen.exe
del /F %~dp0Qt\qtbase\cmake_install.cmake
del /F %~dp0Qt\qtbase\config.tests\arch\CMakeCache.txt
rmdir /S/Q %~dp0Qt\qtbase\config.tests\arch\CMakeFiles\
del /F %~dp0Qt\qtbase\config.tests\arch\Makefile
del /F %~dp0Qt\qtbase\config.tests\arch\architecture_test.exe
del /F %~dp0Qt\qtbase\config.tests\arch\cmake_install.cmake
del /F %~dp0Qt\qtbase\config.tests\cmake_zstd.zstd
rmdir /S/Q %~dp0Qt\qtbase\config.tests\x86_simd_avx512vbmi2\
rmdir /S/Q %~dp0Qt\qtbase\config.tests\x86_simd_vaes\
rmdir /S/Q %~dp0Qt\qtbase\doc\CMakeFiles\
del /F %~dp0Qt\qtbase\doc\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\doc\Makefile
del /F %~dp0Qt\qtbase\doc\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\include\
del /F %~dp0Qt\qtbase\lib\Qt6Core.prl
del /F %~dp0Qt\qtbase\lib\Qt6EntryPoint.prl
rmdir /S/Q %~dp0Qt\qtbase\lib\cmake\
del /F %~dp0Qt\qtbase\lib\libQt6BundledHarfbuzz.a
del /F %~dp0Qt\qtbase\lib\libQt6BundledPcre2.a
del /F %~dp0Qt\qtbase\lib\libQt6BundledZLIB.a
del /F %~dp0Qt\qtbase\lib\libQt6EntryPoint.a
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_ext_freetype.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_ext_harfbuzz.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_ext_libpng.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_ext_pcre2.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_core.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_core_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_devicediscovery_support_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_entrypoint_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_example_icons_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_fb_support_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_freetype_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_gui.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_gui_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_harfbuzz_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_opengl.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_opengl_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_openglwidgets.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_openglwidgets_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_png_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_widgets.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_widgets_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_lib_zlib_private.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qdirect2d.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qgif.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qico.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qminimal.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qwindows.pri
rmdir /S/Q %~dp0Qt\qtbase\mkspecs\preliminary\
del /F %~dp0Qt\qtbase\mkspecs\qconfig.pri
del /F %~dp0Qt\qtbase\mkspecs\qmodule.pri
rmdir /S/Q %~dp0Qt\qtbase\modules\
rmdir /S/Q %~dp0Qt\qtbase\qmake\CMakeFiles\
del /F %~dp0Qt\qtbase\qmake\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\qmake\Makefile
del /F %~dp0Qt\qtbase\qmake\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\Makefile
del /F %~dp0Qt\qtbase\src\3rdparty\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\freetype\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\FreetypePrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\FreetypePrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\FreetypePrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\freetype\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\3rdparty\freetype\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\HarfbuzzPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\HarfbuzzPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\HarfbuzzPrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\libpng\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\Makefile
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\PngPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\PngPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\PngPrivate_syncqt_timestamp
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\libpng\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\3rdparty\libpng\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\pcre2\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\pcre2\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\pcre2\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\pcre2\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\3rdparty\pcre2\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\zlib\CMakeFiles\
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\Makefile
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\ZlibPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\ZlibPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\ZlibPrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\3rdparty\zlib\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\CMakeFiles\
del /F %~dp0Qt\qtbase\src\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\android\CMakeFiles\
del /F %~dp0Qt\qtbase\src\android\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\android\Makefile
del /F %~dp0Qt\qtbase\src\android\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\assets\CMakeFiles\
del /F %~dp0Qt\qtbase\src\assets\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\assets\Makefile
del /F %~dp0Qt\qtbase\src\assets\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\assets\icons\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\assets\icons\CMakeFiles\
del /F %~dp0Qt\qtbase\src\assets\icons\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate.version
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate.version.in
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate.version.private_content
rmdir /S/Q %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate_autogen\
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\assets\icons\ExampleIconsPrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\assets\icons\Makefile
del /F %~dp0Qt\qtbase\src\assets\icons\QtExampleIcons_header_check_exceptions
del /F %~dp0Qt\qtbase\src\assets\icons\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\assets\icons\meta_types\
del /F %~dp0Qt\qtbase\src\assets\icons\preliminary_prl_for_ExampleIconsPrivate_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\assets\icons\preliminary_prl_meta_info_for_ExampleIconsPrivate_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\.doc\
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\.rcc\
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\CMakeFiles\
del /F %~dp0Qt\qtbase\src\corelib\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\corelib\Core.version
del /F %~dp0Qt\qtbase\src\corelib\Core.version.in
del /F %~dp0Qt\qtbase\src\corelib\Core.version.private_content
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\Core_autogen\
del /F %~dp0Qt\qtbase\src\corelib\Core_syncqt_all_args
del /F %~dp0Qt\qtbase\src\corelib\Core_syncqt_args
del /F %~dp0Qt\qtbase\src\corelib\Core_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\corelib\Makefile
del /F %~dp0Qt\qtbase\src\corelib\QtCore_header_check_exceptions
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\corelib\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\corelib\global\qconfig.cpp
del /F %~dp0Qt\qtbase\src\corelib\global\qconfig.h
del /F %~dp0Qt\qtbase\src\corelib\global\qconfig_p.h
del /F %~dp0Qt\qtbase\src\corelib\kernel\moc_qobject.cpp
del /F %~dp0Qt\qtbase\src\corelib\kernel\moc_qobject.cpp.json
del /F %~dp0Qt\qtbase\src\corelib\kernel\moc_qobject.cpp_parameters_RelWithDebInfo
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\meta_types\
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_for_Core_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_for_Core_step2_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_meta_info_for_Core_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\corelib\qt_lib_core_private.pri
del /F %~dp0Qt\qtbase\src\corelib\qtcore-config.h
del /F %~dp0Qt\qtbase\src\corelib\qtcore-config_p.h
del /F %~dp0Qt\qtbase\src\corelib\qtcore_tracepoints_p.h
rmdir /S/Q %~dp0Qt\qtbase\src\entrypoint\CMakeFiles\
del /F %~dp0Qt\qtbase\src\entrypoint\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\entrypoint\Makefile
del /F %~dp0Qt\qtbase\src\entrypoint\Qt6EntryPointMinGW32Target.cmake
del /F %~dp0Qt\qtbase\src\entrypoint\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\entrypoint\preliminary_prl_for_EntryPointImplementation_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\entrypoint\preliminary_prl_for_EntryPointImplementation_step2_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\entrypoint\preliminary_prl_meta_info_for_EntryPointImplementation_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\gui\.doc\
rmdir /S/Q %~dp0Qt\qtbase\src\gui\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\gui\CMakeFiles\
del /F %~dp0Qt\qtbase\src\gui\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\gui\Gui.version
del /F %~dp0Qt\qtbase\src\gui\Gui.version.in
del /F %~dp0Qt\qtbase\src\gui\Gui.version.private_content
rmdir /S/Q %~dp0Qt\qtbase\src\gui\Gui_autogen\
del /F %~dp0Qt\qtbase\src\gui\Gui_syncqt_all_args
del /F %~dp0Qt\qtbase\src\gui\Gui_syncqt_args
del /F %~dp0Qt\qtbase\src\gui\Gui_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\gui\Makefile
del /F %~dp0Qt\qtbase\src\gui\QtGui_header_check_exceptions
rmdir /S/Q %~dp0Qt\qtbase\src\gui\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\gui\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\gui\meta_types\
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_for_Gui_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_meta_info_for_Gui_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\gui\qt_lib_gui_private.pri
del /F %~dp0Qt\qtbase\src\gui\qtgui-config.h
del /F %~dp0Qt\qtbase\src\gui\qtgui-config_p.h
del /F %~dp0Qt\qtbase\src\gui\qtgui_tracepoints_p.h
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\.doc\
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\CMakeFiles\
del /F %~dp0Qt\qtbase\src\opengl\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\opengl\Makefile
del /F %~dp0Qt\qtbase\src\opengl\OpenGL.version
del /F %~dp0Qt\qtbase\src\opengl\OpenGL.version.in
del /F %~dp0Qt\qtbase\src\opengl\OpenGL.version.private_content
del /F %~dp0Qt\qtbase\src\opengl\OpenGL_syncqt_all_args
del /F %~dp0Qt\qtbase\src\opengl\OpenGL_syncqt_args
del /F %~dp0Qt\qtbase\src\opengl\OpenGL_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\opengl\QtOpenGL_header_check_exceptions
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\opengl\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\meta_types\
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_for_OpenGL_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_meta_info_for_OpenGL_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\opengl\qt_lib_opengl_private.pri
del /F %~dp0Qt\qtbase\src\opengl\qtopengl_tracepoints_p.h
rmdir /S/Q %~dp0Qt\qtbase\src\openglwidgets\CMakeFiles\
del /F %~dp0Qt\qtbase\src\openglwidgets\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\openglwidgets\Makefile
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets.version
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets.version.in
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets.version.private_content
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets_syncqt_all_args
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets_syncqt_args
del /F %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\openglwidgets\QtOpenGLWidgets_header_check_exceptions
rmdir /S/Q %~dp0Qt\qtbase\src\openglwidgets\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\openglwidgets\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\openglwidgets\meta_types\
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_for_OpenGLWidgets_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_meta_info_for_OpenGLWidgets_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\openglwidgets\qt_lib_openglwidgets_private.pri
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\CMakeFiles\
del /F %~dp0Qt\qtbase\src\platformsupport\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\platformsupport\Makefile
del /F %~dp0Qt\qtbase\src\platformsupport\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\devicediscovery\CMakeFiles\
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate.version
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate.version.in
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate.version.private_content
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate_autogen\
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\DeviceDiscoverySupportPrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\Makefile
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\QtDeviceDiscoverySupport_header_check_exceptions
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\devicediscovery\meta_types\
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\preliminary_prl_for_DeviceDiscoverySupportPrivate_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\preliminary_prl_meta_info_for_DeviceDiscoverySupportPrivate_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\fbconvenience\CMakeFiles\
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate.version
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate.version.in
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate.version.private_content
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate_autogen\
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate_syncqt_all_args
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate_syncqt_args
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\FbSupportPrivate_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\Makefile
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\QtFbSupport_header_check_exceptions
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\platformsupport\fbconvenience\meta_types\
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\preliminary_prl_for_FbSupportPrivate_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\platformsupport\fbconvenience\preliminary_prl_meta_info_for_FbSupportPrivate_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\Makefile
del /F %~dp0Qt\qtbase\src\plugins\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\generic\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\generic\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\generic\Makefile
del /F %~dp0Qt\qtbase\src\plugins\generic\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\imageformats\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\imageformats\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\imageformats\Makefile
del /F %~dp0Qt\qtbase\src\plugins\imageformats\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\imageformats\gif\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\Makefile
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\QGifPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\QGifPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\QGifPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_for_QGifPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_meta_info_for_QGifPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\imageformats\ico\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\Makefile
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\QICOPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\QICOPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\QICOPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_for_QICOPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_meta_info_for_QICOPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforminputcontexts\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforminputcontexts\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforminputcontexts\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforminputcontexts\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforms\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\direct2d\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\direct2d\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\QWindowsDirect2DIntegrationPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\QWindowsDirect2DIntegrationPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\QWindowsDirect2DIntegrationPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\preliminary_prl_for_QWindowsDirect2DIntegrationPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\preliminary_prl_meta_info_for_QWindowsDirect2DIntegrationPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\minimal\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\QMinimalIntegrationPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\QMinimalIntegrationPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\QMinimalIntegrationPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\preliminary_prl_for_QMinimalIntegrationPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\minimal\preliminary_prl_meta_info_for_QMinimalIntegrationPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\offscreen\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\QOffscreenIntegrationPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\QOffscreenIntegrationPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\QOffscreenIntegrationPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\preliminary_prl_for_QOffscreenIntegrationPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\offscreen\preliminary_prl_meta_info_for_QOffscreenIntegrationPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\windows\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\windows\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\QWindowsIntegrationPlugin.version
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\QWindowsIntegrationPlugin.version.in
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\QWindowsIntegrationPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\preliminary_prl_for_QWindowsIntegrationPlugin_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\preliminary_prl_meta_info_for_QWindowsIntegrationPlugin_RelWithDebInfo.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platformthemes\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platformthemes\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platformthemes\Makefile
del /F %~dp0Qt\qtbase\src\plugins\platformthemes\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\styles\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\styles\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\styles\Makefile
del /F %~dp0Qt\qtbase\src\plugins\styles\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\tools\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\tools\bootstrap\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\bootstrap\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\bootstrap\Makefile
del /F %~dp0Qt\qtbase\src\tools\bootstrap\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\bootstrap\libBootstrap.a
rmdir /S/Q %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\Makefile
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\cmake_automoc_parser_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\cmake_automoc_parser_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\cmake_automoc_parser_resource.rc
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\cmake_automoc_parser_resource.rc.tmp
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\cmake_automoc_parser\libcmake_automoc_parser.dll.a
del /F %~dp0Qt\qtbase\src\tools\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\tools\moc\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\moc\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\moc\Makefile
del /F %~dp0Qt\qtbase\src\tools\moc\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\moc\libmoc.dll.a
del /F %~dp0Qt\qtbase\src\tools\moc\moc_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\moc\moc_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\moc\moc_resource.rc
del /F %~dp0Qt\qtbase\src\tools\moc\moc_resource.rc.tmp
del /F %~dp0Qt\qtbase\src\tools\moc\moc_try_run.bat
del /F %~dp0Qt\qtbase\src\tools\moc\moc_try_run_passed
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qlalr\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\qlalr\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\qlalr\Makefile
del /F %~dp0Qt\qtbase\src\tools\qlalr\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qlalr\qlalr_autogen\
del /F %~dp0Qt\qtbase\src\tools\qlalr\qlalr_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\qlalr\qlalr_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\qlalr\qlalr_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qtpaths\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\qtpaths\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\qtpaths\Makefile
del /F %~dp0Qt\qtbase\src\tools\qtpaths\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_resource.rc.tmp
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_try_run.bat
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qvkgen\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\qvkgen\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\qvkgen\Makefile
del /F %~dp0Qt\qtbase\src\tools\qvkgen\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qvkgen\qvkgen_autogen\
del /F %~dp0Qt\qtbase\src\tools\qvkgen\qvkgen_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\qvkgen\qvkgen_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\qvkgen\qvkgen_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\tools\rcc\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\rcc\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\rcc\Makefile
del /F %~dp0Qt\qtbase\src\tools\rcc\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_resource.rc.tmp
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_try_run.bat
rmdir /S/Q %~dp0Qt\qtbase\src\tools\syncqt\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\syncqt\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\syncqt\Makefile
del /F %~dp0Qt\qtbase\src\tools\syncqt\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\syncqt\syncqt_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\syncqt\syncqt_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\syncqt\syncqt_resource.rc
del /F %~dp0Qt\qtbase\src\tools\syncqt\syncqt_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\tools\tracegen\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\tracegen\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\tracegen\Makefile
del /F %~dp0Qt\qtbase\src\tools\tracegen\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\tracegen\tracegen_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\tracegen\tracegen_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\tracegen\tracegen_resource.rc
del /F %~dp0Qt\qtbase\src\tools\tracegen\tracegen_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\tools\tracepointgen\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\Makefile
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\tracepointgen_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\tracepointgen_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\tracepointgen_resource.rc
del /F %~dp0Qt\qtbase\src\tools\tracepointgen\tracepointgen_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\tools\uic\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\uic\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\uic\Makefile
del /F %~dp0Qt\qtbase\src\tools\uic\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\uic\uic_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\uic\uic_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\uic\uic_resource.rc.tmp
del /F %~dp0Qt\qtbase\src\tools\uic\uic_try_run.bat
rmdir /S/Q %~dp0Qt\qtbase\src\tools\windeployqt\CMakeFiles\
del /F %~dp0Qt\qtbase\src\tools\windeployqt\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\tools\windeployqt\Makefile
del /F %~dp0Qt\qtbase\src\tools\windeployqt\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\tools\windeployqt\windeployqt_longpath.manifest
del /F %~dp0Qt\qtbase\src\tools\windeployqt\windeployqt_longpath.rc
del /F %~dp0Qt\qtbase\src\tools\windeployqt\windeployqt_resource.rc.tmp
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\.doc\
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\CMakeFiles\
del /F %~dp0Qt\qtbase\src\widgets\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\widgets\Makefile
del /F %~dp0Qt\qtbase\src\widgets\QtWidgets_header_check_exceptions
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\RelWithDebInfo\
del /F %~dp0Qt\qtbase\src\widgets\Widgets.version
del /F %~dp0Qt\qtbase\src\widgets\Widgets.version.in
del /F %~dp0Qt\qtbase\src\widgets\Widgets.version.private_content
del /F %~dp0Qt\qtbase\src\widgets\Widgets_syncqt_all_args
del /F %~dp0Qt\qtbase\src\widgets\Widgets_syncqt_args
del /F %~dp0Qt\qtbase\src\widgets\Widgets_syncqt_timestamp
del /F %~dp0Qt\qtbase\src\widgets\cmake_install.cmake
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\meta_types\
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_for_Widgets_step1_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_meta_info_for_Widgets_RelWithDebInfo.txt
del /F %~dp0Qt\qtbase\src\widgets\qt_lib_widgets_private.pri
del /F %~dp0Qt\qtbase\src\widgets\qtwidgets-config.h
del /F %~dp0Qt\qtbase\src\widgets\qtwidgets-config_p.h
del /F %~dp0Qt\qtbase\src\widgets\qtwidgets_tracepoints_p.h
del /F %~dp0Qt\install_manifest.txt
del /F %~dp0Qt\qtbase\bin\qtpaths.exe
del /F %~dp0Qt\qtbase\bin\rcc.exe
del /F %~dp0Qt\qtbase\bin\uic.exe
del /F %~dp0Qt\qtbase\bin\windeployqt.exe
del /F %~dp0Qt\qtbase\lib\Qt6Gui.prl
del /F %~dp0Qt\qtbase\lib\Qt6OpenGL.prl
del /F %~dp0Qt\qtbase\lib\Qt6OpenGLWidgets.prl
del /F %~dp0Qt\qtbase\lib\Qt6Widgets.prl
del /F %~dp0Qt\qtbase\lib\libQt6BundledFreetype.a
del /F %~dp0Qt\qtbase\lib\libQt6BundledLibpng.a
del /F %~dp0Qt\qtbase\lib\libQt6Core.a
del /F %~dp0Qt\qtbase\lib\libQt6Gui.a
del /F %~dp0Qt\qtbase\lib\libQt6OpenGL.a
del /F %~dp0Qt\qtbase\lib\libQt6OpenGLWidgets.a
del /F %~dp0Qt\qtbase\lib\libQt6Widgets.a
rmdir /S/Q %~dp0Qt\qtbase\plugins\
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_for_Gui_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\OpenGL_autogen\
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_for_OpenGL_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\openglwidgets\OpenGLWidgets_autogen\
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_for_OpenGLWidgets_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\imageformats\gif\QGifPlugin_autogen\
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_for_QGifPlugin_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\imageformats\ico\QICOPlugin_autogen\
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_for_QICOPlugin_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\direct2d\QWindowsDirect2DIntegrationPlugin_autogen\
del /F %~dp0Qt\qtbase\src\plugins\platforms\direct2d\preliminary_prl_for_QWindowsDirect2DIntegrationPlugin_step2_RelWithDebInfo.prl
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\windows\QWindowsIntegrationPlugin_autogen\
del /F %~dp0Qt\qtbase\src\plugins\platforms\windows\preliminary_prl_for_QWindowsIntegrationPlugin_step2_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\src\tools\qtpaths\libqtpaths.dll.a
rmdir /S/Q %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_autogen\
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_resource.rc
del /F %~dp0Qt\qtbase\src\tools\qtpaths\qtpaths_try_run_passed
del /F %~dp0Qt\qtbase\src\tools\rcc\librcc.dll.a
rmdir /S/Q %~dp0Qt\qtbase\src\tools\rcc\rcc_autogen\
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_resource.rc
del /F %~dp0Qt\qtbase\src\tools\rcc\rcc_try_run_passed
del /F %~dp0Qt\qtbase\src\tools\uic\libuic.dll.a
rmdir /S/Q %~dp0Qt\qtbase\src\tools\uic\uic_autogen\
del /F %~dp0Qt\qtbase\src\tools\uic\uic_resource.rc
del /F %~dp0Qt\qtbase\src\tools\uic\uic_try_run_passed
del /F %~dp0Qt\qtbase\src\tools\windeployqt\libwindeployqt.dll.a
rmdir /S/Q %~dp0Qt\qtbase\src\tools\windeployqt\windeployqt_autogen\
del /F %~dp0Qt\qtbase\src\tools\windeployqt\windeployqt_resource.rc
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\Widgets_autogen\
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_for_Widgets_step2_RelWithDebInfo.prl
del /F %~dp0Qt\qtbase\config.tests\arch\architecture_test.js
del /F %~dp0Qt\qtbase\config.tests\arch\architecture_test.wasm
del /F %~dp0Qt\qtbase\libexec\qt-cmake-private-install.cmake
del /F %~dp0Qt\qtbase\libexec\qt-wasmtestrunner.py
rmdir /S/Q %~dp0Qt\qtbase\preliminary\
del /F %~dp0Qt\qtbase\bin\target_qt.conf
del /F %~dp0Qt\qtbase\lib\libQt6Core.prl
del /F %~dp0Qt\qtbase\lib\libQt6DeviceDiscoverySupport.a
del /F %~dp0Qt\qtbase\lib\libQt6DeviceDiscoverySupport.prl
del /F %~dp0Qt\qtbase\lib\libQt6Gui.prl
del /F %~dp0Qt\qtbase\lib\libQt6OpenGL.prl
del /F %~dp0Qt\qtbase\lib\libQt6OpenGLWidgets.prl
del /F %~dp0Qt\qtbase\lib\libQt6Widgets.prl
del /F %~dp0Qt\qtbase\mkspecs\modules\qt_plugin_qwasm.pri
del /F %~dp0Qt\qtbase\mkspecs\qdevice.pri
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\freetype\Release\
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\harfbuzz-ng\Release\
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\libpng\Release\
rmdir /S/Q %~dp0Qt\qtbase\src\3rdparty\pcre2\Release\
rmdir /S/Q %~dp0Qt\qtbase\src\corelib\Release\
del /F %~dp0Qt\qtbase\src\corelib\kernel\moc_qobject.cpp_parameters_Release
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_for_Core_step1_Release.prl
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_for_Core_step2_Release.prl
del /F %~dp0Qt\qtbase\src\corelib\preliminary_prl_meta_info_for_Core_Release.txt
rmdir /S/Q %~dp0Qt\qtbase\src\gui\Release\
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_for_Gui_step1_Release.prl
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_for_Gui_step2_Release.prl
del /F %~dp0Qt\qtbase\src\gui\preliminary_prl_meta_info_for_Gui_Release.txt
rmdir /S/Q %~dp0Qt\qtbase\src\opengl\Release\
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_for_OpenGL_step1_Release.prl
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_for_OpenGL_step2_Release.prl
del /F %~dp0Qt\qtbase\src\opengl\preliminary_prl_meta_info_for_OpenGL_Release.txt
rmdir /S/Q %~dp0Qt\qtbase\src\openglwidgets\Release\
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_for_OpenGLWidgets_step1_Release.prl
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_for_OpenGLWidgets_step2_Release.prl
del /F %~dp0Qt\qtbase\src\openglwidgets\preliminary_prl_meta_info_for_OpenGLWidgets_Release.txt
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\preliminary_prl_for_DeviceDiscoverySupportPrivate_step1_Release.prl
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\preliminary_prl_for_DeviceDiscoverySupportPrivate_step2_Release.prl
del /F %~dp0Qt\qtbase\src\platformsupport\devicediscovery\preliminary_prl_meta_info_for_DeviceDiscoverySupportPrivate_Release.txt
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_for_QGifPlugin_step1_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_for_QGifPlugin_step2_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\gif\preliminary_prl_meta_info_for_QGifPlugin_Release.txt
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_for_QICOPlugin_step1_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_for_QICOPlugin_step2_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\imageformats\ico\preliminary_prl_meta_info_for_QICOPlugin_Release.txt
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\wasm\.qt\
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\wasm\CMakeFiles\
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\CTestTestfile.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\Makefile
rmdir /S/Q %~dp0Qt\qtbase\src\plugins\platforms\wasm\QWasmIntegrationPlugin_autogen\
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\QWasmIntegrationPlugin_init.cpp
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\cmake_install.cmake
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\preliminary_prl_for_QWasmIntegrationPlugin_step1_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\preliminary_prl_for_QWasmIntegrationPlugin_step2_Release.prl
del /F %~dp0Qt\qtbase\src\plugins\platforms\wasm\preliminary_prl_meta_info_for_QWasmIntegrationPlugin_Release.txt
rmdir /S/Q %~dp0Qt\qtbase\src\widgets\Release\
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_for_Widgets_step1_Release.prl
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_for_Widgets_step2_Release.prl
del /F %~dp0Qt\qtbase\src\widgets\preliminary_prl_meta_info_for_Widgets_Release.txt
